# Generated by Django 3.1.3 on 2020-11-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20201112_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option',
            field=models.ManyToManyField(to='quiz_app.Options'),
        ),
    ]
